# RNG Provider Configuration
# Options: 
#  - uniform: Standard uniform distribution (0-1)
#  - normal: Normal distribution with mean 0.5, std dev 0.15, clamped to (0-1) 
#  - external-api: Uses an external HTTP API to provide random numbers
rng_provider: normal 
# rng_provider: external-api

# API URL (REQUIRED when rng_provider is external-api)
# The API endpoint must return JSON with a 'random' field containing a number between 0-1
# Example: {"random": 0.42}
api_url: http://localhost:8000/random

# Run Directory (where outputs will be saved)
# run_dir: runs/default

# Model Configuration
# model: gemma-2-2b-it  # See model_paths in run.py for available shortcuts
model: gemma-2-2b  # See model_paths in run.py for available shortcuts

# Number of tokens to generate (optional)
num_tokens: 100

# Prompt
prompt: "Tell me about the history of artificial intelligence"
