# RNG Provider Configuration
# Options: uniform, normal, external-api
rng_provider: normal 

# API URL (required when rng_provider is external-api)
# api_url: http://localhost:8000/random

# Run Directory (where outputs will be saved)
# run_dir: runs/default

# Model Configuration
model: gemma-2-2b-it  # See model_paths in run.py for available shortcuts

# Number of tokens to generate (optional)
num_tokens: 100

# Prompt
prompt: "Tell me about the history of artificial intelligence"
