# RNG Provider Configuration
rng_provider: uniform  # Options: uniform, normal

# # Run Directory (where outputs will be saved)
# run_dir: runs/default

# Model Configuration
model: gemma-2-2b  # See model_paths in run.py for available shortcuts

# Prompt
prompt: "Tell me about the history of artificial intelligence"
